=== Pradyum-19/Tech-Rev/community.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="com">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="info" maxOccurs="unbounded">
              <xs:complexType>
                 <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="role" type="xs:string"/>
                    <xs:element name="exp" type="xs:string"/>
            		    <xs:element name="working">
            		    <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="Yes"/>
                            <xs:enumeration value="No"/>
                          </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
          		 </xs:sequence>
        	  </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
</xs:element>
</xs:schema>

=== Pradyum-19/Tech-Rev/community.xml
<?xml version="1.0" encoding="UTF-8"?> 
<?xml-stylesheet type="text/xsl" href="community.xsl"?>
 <com xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="community.xsd">
  <info> 
   <name>John</name> 
   <role>CEO</role> 
   <exp>2 Year</exp> 
   <working>Yes</working>
  </info>
  <info> 
   <name>Smith</name> 
   <role>COO</role> 
   <exp>1 Year</exp> 
   <working>Yes</working>
  </info> 
  <info> 
   <name>Paul</name> 
   <role>Analyst</role> 
   <exp>1 Year</exp> 
   <working>Yes</working>
  </info>  
 </com>
